dist: xenial

before_install:
  - sudo apt-get install -y ansible docker
  - wget https://releases.hashicorp.com/vagrant/2.0.4/vagrant_2.0.4_x86_64.deb
  - sudo dpkg -i vagrant_2.0.4_x86_64.deb

script: ./.hypress/scripts/pre-commit.sh
