---
- name: Setup hypress machine
  hosts: 127.0.0.1
  become: true

  tasks:
  - name: Install nodejs
    package:
      name: nodejs
      state: present

  - name: Install npm
    package:
      name: npm
      state: present

  - name: Install apache2
    package:
      name: apache2
      state: present

  - name: Install PHP7
    package:
      name: php7.2
      state: present
    notify:
      - restart apache2

  - name: Install MySQL
    package:
      name: mysql-server
      state: present
    notify:
      - restart apache2

  - name: Install PHP MySQL
    package:
      name: php-mysql
      state: present
    notify:
      - restart apache2

  - name: Start MySQL
    service: name=mysql
             enabled=yes
             state=started

  - name: Install phpMyAdmin
    package:
      name: phpmyadmin
      state: present

  - name: Install python-mysqldb
    package:
      name: python-mysqldb
      state: present

  - name: Setup MySQL user
    mysql_user:
      name: hypress
      password: hypress
      priv: '*.*:ALL'
      state: present

  - name: Setup MySQL database
    mysql_db:
      name: hypress
      state: present

  - name: Add hypress virtual host
    copy:
      dest: "/etc/apache2/sites-available/hypress.conf"
      content: |
        <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            ServerName localhost
            DocumentRoot /host-machine/.hypress/htdocs/wp
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined

            Alias /phpmyadmin "/usr/share/phpmyadmin"
            <Directory /usr/share/phpmyadmin>
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
            </Directory>

            <Directory /host-machine/.hypress/htdocs>
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
            </Directory>
        </VirtualHost>

  - stat:
      path: /host-machine/hypress.local.pem
    register: result

  - name: Add hypress virtual host for ssl
    copy:
      dest: "/etc/apache2/sites-available/hypress-ssl.conf"
      content: |
                <VirtualHost *:443>
                    SSLEngine on
                    SSLCertificateFile /host-machine/hypress.local.pem
                    SSLCertificateKeyFile /host-machine/hypress.local-key.pem

                    ServerAdmin webmaster@localhost
                    ServerName localhost
                    DocumentRoot /host-machine/.hypress/htdocs/wp
                    ErrorLog ${APACHE_LOG_DIR}/error.log
                    CustomLog ${APACHE_LOG_DIR}/access.log combined

                    Alias /phpmyadmin "/usr/share/phpmyadmin"
                    <Directory /usr/share/phpmyadmin>
                      Options Indexes FollowSymLinks
                      AllowOverride None
                      Require all granted
                    </Directory>

                    <Directory /host-machine/.hypress/htdocs>
                      Options Indexes FollowSymLinks
                      AllowOverride None
                      Require all granted
                    </Directory>
                </VirtualHost>
    when: result.stat.exists == true

  - name: a2enmod rewrite
    command: a2enmod rewrite
    notify:
      - restart apache2

  - name: a2enmod ssl
    command: a2enmod ssl
    notify:
      - restart apache2

  - name: a2ensite hypress
    command: a2ensite hypress
    notify:
      - restart apache2

  - name: a2ensite hypress-ssl
    command: a2ensite hypress-ssl
    notify:
      - restart apache2

  - name: a2dissite 000-default
    command: a2dissite 000-default
    notify:
      - restart apache2

  - stat:
      path: /usr/local/bin/composer
    register: result

  - name: Install composer
    shell: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php
            mv composer.phar /usr/local/bin/composer
            php -r "unlink('composer-setup.php');"
    when: result.stat.exists == false

  - name: Install WordPress
    shell: |
            cd /host-machine/
            composer install

  - stat:
      path: /usr/local/bin/wp
    register: result

  - name: Download WP-CLI
    get_url:
      url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      dest: /home/vagrant/wp-cli.phar
    when: result.stat.exists == false

  - name: Adjust WP CLI file permissions
    file:
      path: /home/vagrant/wp-cli.phar
      mode: +x
    when: result.stat.exists == false

  - name: Install WP-CLI
    shell: |
            mv /home/vagrant/wp-cli.phar /usr/local/bin/wp
    when: result.stat.exists == false

  - stat:
      path: /host-machine/.hypress/htdocs/wp/wp-content/themes/hypress
    register: result

  - name: Setup symlink to source
    shell: |
      cd /host-machine
      ln -s ../../../../../src ./.hypress/htdocs/wp/wp-content/themes/hypress
    when: result.stat.exists == false

  - name: Run npm install
    become_user: vagrant
    shell: |
      cd /host-machine
      npm install

  - name: Add startup script
    cron:
      name: "startup script"
      special_time: reboot
      job: "/host-machine/.hypress/scripts/startup.sh"

  - name: Adjust startup script file permissions
    file:
      path: /host-machine/.hypress/scripts/startup.sh
      mode: +x

  - name: Run startup script
    shell: |
      /host-machine/.hypress/scripts/startup.sh

  - name: Install WordPress instance
    become_user: vagrant
    shell: |
            cd /host-machine/.hypress/htdocs/wp
            if ! $(wp core is-installed); then
              wp core install --admin_user=hypress --admin_password=hypress --url=192.168.33.10 --title=hypress --admin_email=root@example.com
              wp plugin uninstall hello
              wp plugin uninstall akismet
              wp post delete 1 2 --force
              wp theme activate hypress
            fi

  handlers:
  - name: restart apache2
    service: name=apache2
             state=restarted
